### ISSUE TITLE
[suggestion] Fix impossible to launch voxelmap 1.12.2 on gdlauncher

### ISSUE THREAD

**Issue by quentin452** [ACGaming/VoxelMapFixes#1]
![image](https://user-images.githubusercontent.com/42176772/192195675-ac1e69eb-db78-4e0e-9a0a-79250eda16d2.png)

**Comment by ACGaming** [comment]
Was doubtful at first but this issue really is reproducable with the GDLauncher. JavaScript moment!

However, it seems you can change the startup method to `Symlink` in the launcher settings to get a workaround for issues like these: ![Minecraft Startup Method](https://i.imgur.com/CR9yPgG.png)

**Comment by quentin452** [comment]
ok
